development:
  clients:
    default:
      database: <%= ENV["MONGO_DB"] %>
      hosts:
        - <%= ENV["MONGO_HOST"] %>:<%= ENV["MONGO_PORT"] %>
      options:
        server_selection_timeout: 1
